### ISSUE TITLE
Ability to use emmet to expand html elements

### ISSUE THREAD

**Issue by purplecones** [Raathigesh/SemanticEdit#10]
Hey this is an awesome tool! I'm definitely going to be using it.

One thing I'm missing though is https://github.com/emmetio/emmet capabilities so that the markup can be written up quickly. Would be great to see this as an addition.

**Comment by Raathigesh** [comment]
This is a great idea! Right now I won't be able to focus on it! Would you be interested in implementing this via a PR ?

**Comment by purplecones** [comment]
I'll look into it :-)
