### ISSUE TITLE
Ability to share a composition by URL

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/SemanticEdit#3]
Ability to share a composition by URL would be very usefull to quickly share ideas around

**Comment by samuelandert** [comment]
+1

**Comment by samuelandert** [comment]
I think it would be great to store a composition in the database as a json file, in order to be able to add simple versioning

**Comment by Raathigesh** [comment]
I started working on a client side share feature where the composition is shared through the URL (Like typescript [playground does](http://www.typescriptlang.org/play/index.html)) but never really got around to completing it. Will try to address in the near future if time permits.
