### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by samuelandert** [Raathigesh/SemanticEdit#5]
Hey Raathigesh,
I am really new to programming and just started to mess around with a little bit of code. But as far as I can judge, what you are creating with SemanticEdit is huge thing, which I was searching for already for a long time, so I would like to support. Is there anything easy or simple I can do some improvements? If you are guiding me through, I gladly help!
Best
Sam

**Comment by Raathigesh** [comment]
Hey Samsemilio,

**Comment by Raathigesh** [comment]
Hello Samsemilio,
Thank you showing interest  to help with SemanticEdit. 

SemanticEdit client is developed in ReactJS. How familiar are you with ReactJS?  If you wish you could start by taking a feature like [this](https://github.com/Raathigesh/SemanticEdit/issues/6)

Or If you have any new ideas, we could discuss and then you can implement it.

Thanks,
Raathigeshan

**Comment by samuelandert** [comment]
I have not worked yet with react, just played around with meteor blaze and semantic ui. I will do try to go for some tutorials and come back, once I understood the concept.

**Comment by samuelandert** [comment]
My ultimative goal would be to create fully working react views inside the SemanticEditor and then store them in json documents in the database. To then create a git like forking and pull-request style collaboration mechanism between users on those views. 
So basically every edit to a view, that is not my own view, would create a forked variation and an automatic pull-request to the maintainer of that view. 
Are you heading for the same idea?

**Comment by Raathigesh** [comment]
[This egghead tutorials](https://egghead.io/series/react-fundamentals) are prettry great.

**Comment by samuelandert** [comment]
Thank you very much!
