### ISSUE TITLE
Have an option to resolve images from semantic-ui.com

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/SemanticEdit#6]
Semantic UI documentation has relative image URL as below.

`<img src="/images/avatar2/large/kristy.png">`

So when we copy paste the markup directyly we have to change the URL to absolute as below manually

`<img src="http://semantic-ui.com/images/avatar2/large/kristy.png">`

It would be nice to have an option (Checkbox or a Toggle), when checked, will automatically change the image URL's to absolute URL.

**Comment by samuelandert** [comment]
What do you think about making them available locally and just put them into the public folder of your meteor application?
